### ISSUE TITLE
Converted bevfl not loading in TOTK

### ISSUE THREAD

**Issue by MediaMoots** [NCF-Library/EvflLibrary#1]
Some files after conversion does not load in TOTK

For example DmF_SY_FairyWorking.bfevfl

After converting to Json and back to bevfl with no edits the resulting file does not load when talking to a great fairy.
![image](https://github.com/NCF-Library/BfevLibrary/assets/81146974/889204d4-bb3a-4fdb-aaa0-2a2cd1948af9)
There seems to be some issue with this part of the files, left is the original, right is the converted file.

**Comment by MediaMoots** [comment]
@ArchLeaders Hello, I was wondering if there is a fix for this yet?
Thanks

**Comment by ArchLeaders** [comment]
Nope, issue is still open so it hasn't been fixed. And since school has started, it'll be a while until I have time to work on it.

**Comment by ArchLeaders** [comment]
Fixed in https://github.com/NCF-Library/BfevLibrary/commit/61d3201bd2932c88aa6f01a7ea0c8cf63e0e0446
